### ISSUE TITLE
portieris must be disabled when all its pods crashes (delete webhook)

### ISSUE THREAD

**Issue by rubroboletus** [IBM/portieris#112]
When all running pods of portieris itself crash, webhook become show stopper for starting portieris pods itself (failurePolicy=fail). All K8s is then blocked. Consider adding label to webhook for namespace running portieris and filtering it (namespaceSelector.matchExpression,......) or updating failurePolicy=Ignore with long timeout.

**Comment by molepigeon** [comment]
Hi - thanks for reporting this. This has been an issue on our internal backlog for some time, it looks like it hasn't been replicated on the public repo before though.

The failure policy is "fail" deliberately, to prevent a denial-of-service style attack from allowing an untrusted workload to be permitted onto the cluster.

We need to allow Portieris to restart without making something that you can use to bypass the admission webhook in other places. If we were to use a namespaceSelector, we'd need users to treat permission to edit namespaces as a very trusted operation (and lock it down with RBAC accordingly), because if we can exclude the Portieris install namespace, others can exclude other namespaces where they want to run their stuff by putting the same label on them. Come to think of it, that'd be the case for other things that could be part of someone's cluster security posture, like the Istio sidecar injector, so that's probably acceptable.

@sjhx what do you think?

**Comment by sjhx** [comment]
The proposal is to allow a namespace to be excluded from portieris enforcement by matching a label? Given that we allow per namespace policies anyway, I am not sure what this adds other than complexity which is not good in a security service.

**Comment by rubroboletus** [comment]
@sjhx when Portieris pods are down, because of K8s disaster or other reason, there is no way to start any new container, even Portieris one. Your portieris policy will not work, because there is no running portieris pod.
Try it. Install Portieris, setup any rules and delete all portieris pods. With current setup (failurePolicy: fail in admission webhook) K8s will not start any pod, deployment, ...

**Comment by sjhx** [comment]
My bad @rubroboletus , I see your point.
When you find yourself in that situation the fix would to delete the mutatingwebhookconfiguration, which is a simple step but may have downsides such as allowing all deployments until such time as portieris is back in place.
If we want to do this then I think I would prefer an explicit reference to say a "portieris" namespace rather than a label selector which would be open to exploitation despite the ability to RBAC it.

**Comment by sjhx** [comment]
failurePolicy=ignore with long timeout is also worth considering since there will be audit logs to see this has occurred but has the downside that non-policy deployments in other namespaces may also be allowed

**Comment by sjhx** [comment]
Another thought is that this should be an install time option, there will be those that cannot accept that a label will bypass security and those want it.

**Comment by wjwilson-ibm** [comment]
When attempting to apply updates to our cluster, our pods all went down as described above.  Following the instructions here - https://ibm.biz/master_webhook, I identified Portieris as the issue.  Therefore I uninstalled Portieris entirely and then the pods were recreated again.  Following this issue.

**Comment by wjwilson-ibm** [comment]
Continuing to watch for a resolution.

**Comment by sjhx** [comment]
There are two options now to mitigate this issue, `--set webhooks.FailurePolicy=Ignore` or `--set AllowAdmissionSkip=true`, I don't expect further development on this issue, closing.
