### ISSUE TITLE
ImagePullSecret is not decoded correctly. 

### ISSUE THREAD

**Issue by tinaselenge** [IBM/portieris#174]
### What commit ID of Portieris did you experience the problem with?
Release 0.8.0
### What went wrong?
Portieris is not decoding the registry secret correctly therefore results in unauthorised error with valid credentials.  Our registry secret looks like this (Kubernetes pulls our images with this secret without a problem):
```
{"auths":{"registry.ng.bluemix.net":{"auth":"xxx"}}}
```
`xxx` is base64 and decodes to `iamapikey:yyy`. It looks like the auth is taken straight out the json without base64 decoding.
https://github.com/IBM/portieris/blob/master/pkg/kubernetes/secret.go#L68
### What should have happened differently?
auth value should have been decoded first. 

### How can it be reproduced?
Create a secret with encoded fields in json. 
```
{"auths":{"registry.ng.bluemix.net":{"auth":"xxx"}}}
```

**Comment by dnwe** [comment]
To elaborate a little. I believe the specific issue here is that Portieris only ever looks at the `username` and `password` fields in the `.dockerconfigjson` and never checks the base64-encoded `auth` field at all.

https://github.com/IBM/portieris/blob/c32945ab5997321054c16b8bc0fe8c47efaa911c/pkg/kubernetes/secret.go#L87-L88

In our case, our secret doesn't have any username or password fields and only has the base64-encoded "auth" field.
```
{"auths":{"registry.ng.bluemix.net":{"auth":"aWFtYXBpa2V5OmV4YW1wbGVwYXNzd29yZA=="}}}
```
(base64 `iamapikey:examplepassword`)

Kubernetes' [pkg/credentialprovider](https://github.com/kubernetes/kubernetes/tree/master/pkg/credentialprovider) is happy with this as it only actually _requires_ that either the base64-encoded `auth` field is present, or the `username` and `password` fields are present.

I note from their tests that if the "auth" field _is_ present then kube will actually use whatever value it finds there in preference to the username and password fields, and will override them

[kubernetes/kubernetes/pkg/credentialprovider/config_test.go#L152-L162](https://github.com/kubernetes/kubernetes/blob/a95d04993a79f9f2327ec0c86a2ac654e98228a8/pkg/credentialprovider/config_test.go#L152-L162)
```go
// auth field overrides username & password
{
	// Fake values for testing.
	input: []byte(`{"username": "foo", "password": "bar", "auth": "cGluZzpwb25n", "email": "foo@example.com"}`),
	expect: DockerConfigEntry{
		Username: "ping",
		Password: "pong",
		Email:    "foo@example.com",
	},
	fail: false,
},
```
Where `ping:pong` base64-encoded in the auth field overrides the `foo:bar` found in the username+password fields.


So I think the fix for Portieris would be to default to using the auth field if present, base64-decoding it and splitting on `:` (probably using the http pkg BasicAuth func), and fallback to looking at the username+password fields if those are present.

**Comment by jhart1685** [comment]
Fixed by PR 175 - will close this issue.
