### ISSUE TITLE
Templating of namespace name via values inconsistent with Helm -n

### ISSUE THREAD

**Issue by jhart1685** [IBM/portieris#185]
### What commit ID of Portieris did you experience the problem with?
0.8.1

### What went wrong?
The instructions (in the readme) to install say to do `helm install portieris --create-namespace --namespace portieris helm/portieris` 
If you follow these instructions, Helm creates the namespace, and then the pre-install namespace hook complains that it already exists. i.e. `--create-namespace` **must not** be specified.
Moreover the `--namespace` option sets the `.Release.Namespace` to `portieris` , but the templates all act on `.Values.namespace` instead. So it is not clear that `--namespace` is a meaningful thing to specify on version 0.8.1 of Portieris.

### What should have happened differently?
The templating inside Portieris should be consistent with the install instructions. (Currently they seem to be mutually exclusive).
Ideally, it would be good if both the templating and instructions can be made consistent with the Helm `--create-namespace` and `--namespace` options.

### How can it be reproduced?
`helm install portieris --create-namespace --namespace portieris helm/portieris` 

### Any other relevant information
This can be worked around by simply running `helm install portieris helm/portieris` instead.

**Comment by sjhx** [comment]
It is currently possible to have a different namespace used to record the Helm release information to that in which Portieris runs, due to the use of .Value.namespace rather than .Release.Namespace in the templates. This does not cause a functional problem and not even visible if both values are set to "portieris" as they generally are. 
However it plays into a bigger problem as follows:

Prior to 0.8.1:
The install namespace was managed outside of the Helm assets either by pre-existing or using --create-namespace.
Hyperkube based hook jobs were used to define the CRD's and install the webhook, this meant that the webhook in particular was created more slowly and generally the Portieris pods were able to start without being passed by thier own webhook. 

In 0.8.1
The install namespace is managed in Helm templates so that a lable can be created on it in support of "AllowAdmissionSkip" value and associated namespace selector on the webhook, however this conflicts with the direction of Helm 3 e.g. https://github.com/helm/helm/issues/4456
Hook jobs are no longer used and CRD's and the MutatingWebhookConfiguration is create in Helm templates, this means that:
 - Helm 3 is required.
 - 3rd party Hyperkube image is not longer part of the install process and does not need Portieris policy or lead to some of the issues with hook jobs hanging which was previously seen. 
 - The webHook is created rapidly and generally fast enough that the Portieris Pods themselves are blocked by the webhook they are supposed to provide unless "AllowAdmissionSkip" is defined, leading to install deadlock, or making "AllowAdmissionSkip" mandatory.

Proposal:
1. Use .Release.Namespace in place of .Values.namespace where present in templates. 
2. Remove Namespace template to be consistent with Helm best practice and use --namespace and --create-namespace where necessary. 
3. Replace the AllowAdmissionSkip feature and replace it with a webhook default of "FailurePolicy: Ignore" or v1 equivalent. which will allow Portieris to install reliably.
4. Place a huge warning that users should edit the webhook policy to "FaliurePolicy: Fail" once Portieris is installed and they are looking to use in production for security (otherwise vulnerable to DOS bypass). 
5. Consider moving away from Helm install to an operator with finer grained management of the webhook configuration, e.g. webhook would be installed after pods become ready.

**Comment by molepigeon** [comment]
Re steps 3 and 4: If all the portieris pods are down the service times out, which also happens if the failurepolicy is ignore. That causes pod creations to time out. The namespace selector allows it to quickly skip the critical things so that those pods get created and the webhook can start working to admit everything else.

So changing the default failurepolicy to ignore isn't a drop-in replacement IMO.

We could alternatively not apply the admissionskip label to the portieris namespace in the chart and document doing so as part of the install process. It means that installing Portieris isn't a one-command job anymore but I suspect we've gotten to the point where we need some other way of configuring it.

Re step 5: An operator would solve the namespace labelling issues, but it would also present its own. You'd have an app that would need the RBAC permission to create pods, so that'd need to be secured appropriately. Plus if that goes in the Portieris namespace then we kinda still have the same situation again. Although it's less of a big deal and we could probably go back to saying `helm install --namespace portieris --create-namespace` for that bit.

**Comment by jhart1685** [comment]
Thanks for the write-up, @sjhx , your proposal sounds good to me.
