### ISSUE TITLE
Run Portieris without Helm

### ISSUE THREAD

**Issue by ArjonBu** [IBM/portieris#45]
Hello, 
Is it possible to run Portieris without Helm?

**Comment by molepigeon** [comment]
We only publish the deployment files as part of the chart at the moment, but you can template them yourself and run them against your cluster if you don't want to have Tiller in your cluster.

If you have the Helm client, you can run `helm template` against the chart to get a series of yamls that you can execute against the cluster. An example of the output that you can expect is [this](https://github.com/controlplaneio/workshop-2018-kc-seattle-secure-kubernetes-deployment-pipelines/blob/master/setup/portieris.yaml), although it's best to do it yourself to make sure you get the latest version of all the files.

**Comment by ArjonBu** [comment]
Thanks. I don't seem to understand what SSL certificate is needed there. I see serverCert.pem, serverKey.pem and ca.pem.

**Comment by ArjonBu** [comment]
Also, I don't understand the connection of this SSL and the caBundle for the MutatingWebhookConfiguration. Can you please make it more clear in the docs?

**Comment by molepigeon** [comment]
Sorry, looks like we did miss that in the readme. I've raised a PR to add a step to the install docs about setting up the certs.

Portieris exposes a REST application that the Kubernetes API server uses to send admission requests. That connection is HTTPS, and so Portieris needs to present a certificate during the SSL handshake between itself and the Kubernetes API server.

You can use the `gencerts` script to create new SSL certificates and put them in the right places in the chart. It generates a CA certificate (which is given to the Kubernetes API server so that it expects Portieris' certificate to be signed using that CA cert), and then a certificate that's signed using the CA (for Portieris to present when the Kube API server connects) and a corresponding private key (so that Portieris can complete the SSL handshake).

Generating new certificates is strongly recommended; the existing certificate and private key are available in this repo, so an attacker could use that information to falsely identify as Portieris if the certificates are not replaced.

**Comment by ArjonBu** [comment]
There is a problem with the script
```
bash-3.2$ bash gencerts portieris
usage: yq [-h] [--yaml-output] [--width WIDTH] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'name': [Errno 2] No such file or directory: 'name'
```

Does it need the name like "portieris.kube-system.svc"? I also want to deploy it on kube-system.

**Comment by ArjonBu** [comment]
Changed the script manually. Maybe you can remove the yq dependency completely. Also the namespace is hardcoded. Maybe make it as a var?

**Comment by molepigeon** [comment]
From the yq error, I suspect you have https://github.com/kislyuk/yq version of yq installed. There's another yq with a different syntax: https://github.com/mikefarah/yq - and the mikefarah one is the one that is needed it seems.

It sounds like you've already made some of the changes you suggested - feel free to pull request your changes if you'd like!

**Comment by ArjonBu** [comment]
I just hardcoded the service name for now. I will definitely make a pull request when I change the script.
