### ISSUE TITLE
mutatingwebhook with invalid CA after helm chart reinstall and pod restart

### ISSUE THREAD

**Issue by OrlinVasilev** [IBM/portieris#58]
### What commit ID of Portieris did you experience the problem with?
latest
### What went wrong?
after redpolyment the helm chart mutating web hook is not fixed with the new CA in the CM
### What should have happened differently?
mutatingwebhook must be updated with the new CA
### How can it be reproduced?
just redeploy the portieris so new certificates are generated and restart the pods
### Any other relevant information
dumoing the CM and applying the config fixes the problem but that should be automated

**Comment by molepigeon** [comment]
Hi, thanks for the report. I think the issue here is that the jobs to create the webhooks only run `post-install`. If we make the hook run `post-upgrade` as well, I think that it'll pick up these changes as expected. I'm not sure what side effects that'll have, if any, so it'll need testing.

I'd expect that `portieris/helm/portieris/templates/crd-creation/create-crds.yaml` needs to have:
```yaml
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
```

**Comment by OrlinVasilev** [comment]
@molepigeon yeah that's one solution we came up with .. the other one is to use already existing CA and just on upgrade to re-issue new certificates from the same CA .. maybe I can submit the PR if you want ?

**Comment by molepigeon** [comment]
I think you'd still need to have the helm hook run post-upgrade in case a user needs to change their CA cert for any reason.

Feel free to submit the PR if you're looking at it, but I'll do some experimentation anyway just to make sure it behaves as expected.
