### ISSUE TITLE
could not rotate trust to a new trusted root

### ISSUE THREAD

**Issue by OrlinVasilev** [IBM/portieris#64]
### What went wrong?
Portieris is failing to communicate with Notary
When ImagePolicy is enforced 
getting this error:

Error: UPGRADE FAILED: Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request:
Deny "<OBSCURED_REGISTRY>/heapster:v0.20.0", failed to get content trust information: could not rotate trust to a new trusted root: failed to validate data with current trusted certificates

### How can it be reproduced?
-
### Any other relevant information
-

**Comment by molepigeon** [comment]
Hi - I've seen this before, that error has come out of the Notary code when we call it asking for trust data for your images.

Portieris shouldn't be trying to do root key rotation - and it doesn't have enough information to do it. This probably means that there's some old or otherwise weird data in the trust cache. The cache isn't persisted, so it'll be cleaned out by re-creating the pods. Please could you try triggering a rolling restart of the Portieris pods by adding an annotation to the deployment?

```bash
kubectl patch deployment ${DEPLOYMENT_NAME} -p'{"spec":{"template":{"metadata":{"annotations":{"restarted":"'$(date +%s)'"}}}}}}' -n ${DEPLOYMENT_NAMESPACE}
```

(note: replace the DEPLOYMENT_NAME and DEPLOYMENT_NAMESPACE variables with the correct values for your installation)

**Comment by OrlinVasilev** [comment]
looks like working workaround :) thanks
