### ISSUE TITLE
Portieris do not allow new master nodes of cluster to come up If all of them are down.

### ISSUE THREAD

**Issue by ShubhamAgarwal1616** [IBM/portieris#97]
### What commit ID of Portieris did you experience the problem with?
release 0.6.0

### What went wrong?
We installed Portieris on a KOPS cluster with version 1.16.0. When we are bringing down all master nodes of our cluster, new master nodes are not able to create pods of API-server, Kube-proxy, etc. The error that comes in the logs as follows :

Failed creating a mirror pod for "kube-proxy-ip-<node-ip>.ap-south-1.compute.internal_kube-system": Internal error occurred: failed calling webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com": Post https://portieris.portieris.svc:443/admit?timeout=30s: connect: connection refused

### What should have happened differently?
If all the masters are down for a cluster new masters should come up properly with all relevant pods.

### How can it be reproduced?
Install Portieris in any KOPS cluster and make all masters nodes down.

**Comment by molepigeon** [comment]
Portieris needs to be able to talk to the API server to work. It looks like the admission webhook isn't working in your case, likely Portieris isn't running either.

The admission webhook for Portieris is configured to fail when it's not working, so that a malicious party can't DoS the connection between the cluster and Portieris in order to get a forbidden image to run. However, that option is configurable in the webhook configuration, so you can temporarily allow admissions so that your control plane pods can restart.

Run `kubectl edit MutatingWebhookConfiguration image-admission-config` and change `failurePolicy` to `Ignore`, then save the changes. Then your pods should start appearing again. Once they've recovered, you can change the `failurePolicy` back to `Fail`.

**Comment by sjhx** [comment]
I am closing this issue in the absence of further comment, question is answered, no change proposed.
